### ISSUE TITLE
15.7 and 22.6 - disallow hacky boolean conversion?

### ISSUE THREAD

**Issue by mjomble** [gtap-dev/javascript#10]
15.7 lists this as a good example:

```typescript
const bar = !!c;
```

and 22.6 considers the `!!` syntax better than the more explicit alternative:

```typescript
// good
const hasAge = Boolean(age);

// best
const hasAge = !!age;
```

In my opinion, this syntax falls into a hacky category with other examples listen in the doc of ESLint's [no-implicit-coercion](https://eslint.org/docs/rules/no-implicit-coercion) rule.

I propose using this ESLint rule and disallowing the `!!` syntax.

**Comment by Vladisls** [comment]
I would suggest to continue using `!!` as `Boolean` would not introduce any benefits.

**Comment by mihkeleidast** [comment]
I generally feel that the double bang syntax is pretty explicit (in comparison to the ESLint naming of "no-implicit-coercion" rule). It's also shorter, so easier to write.

**Comment by mjomble** [comment]
Fair enough 🙂
