### ISSUE TITLE
23.9 - readability of acronyms

### ISSUE THREAD

**Issue by mjomble** [gtap-dev/javascript#12]
The rationale for this rule is that `HTTPRequests`, for example, is more readable than `HttpRequests`.
But readability tends to be quite subjective and for me, it's the other way around. Probably just because I've been using this convention for a long time.

Perhaps we could put this to a vote to see which one is preferred among our developers?

React with 🚀 if you think `HTTPRequests` is more readable
React with 👀 if you think `HttpRequests` is more readable

**Comment by mihkeleidast** [comment]
airbnb/javascript#653 brought `XMLHttpRequest` as an "official" example so it's definitely subjective :)

**Comment by Vladisls** [comment]
I propose a third option. Remove the rule and give the right to decide to the developer (keeping in mind that in the context of one project the same names should be cased in the same way).

**Comment by mihkeleidast** [comment]
Another point: `HttpRequest` is enforceable with linters (as it's definitely PascalCase), `HTTPRequest` is not, since linters do not know about valid acronyms and abbrevations.
